"""Add AMBIGUOUS status

Revision ID: 146c8e1f3b8e
Revises: 
Create Date: 2026-04-23 07:36:38.159195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '146c8e1f3b8e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parameters', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('generated_code', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('modification_command', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('parent_prompt_id', sa.Integer(), nullable=True))
#        batch_op.create_foreign_key('fk_prompt_parent', 'prompt_requests', ['parent_prompt_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table('prompt_requests', schema=None) as batch_op:
#        batch_op.drop_constraint('fk_prompt_parent', type_='foreignkey')
        batch_op.drop_column('parent_prompt_id')
        batch_op.drop_column('modification_command')
        batch_op.drop_column('generated_code')
        batch_op.drop_column('parameters')

    # ### end Alembic commands ###
