"""link imported assets to prompt requests

Revision ID: c9dad017f8e4
Revises: 6263594b81ad
Create Date: 2026-05-07 09:40:38.265349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9dad017f8e4'
down_revision = '6263594b81ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imported_asset_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_prompt_requests_imported_asset_id_imported_assets',
            'imported_assets',
            ['imported_asset_id'],
            ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt_requests', schema=None) as batch_op:
        batch_op.drop_constraint(
            'fk_prompt_requests_imported_asset_id_imported_assets',
            type_='foreignkey'
        )
        batch_op.drop_column('imported_asset_id')

    # ### end Alembic commands ###
